---
# Config Main of LockedItem
perm-message: You are not allowed to use this command!
lock-message: Your item has been locked successfully!
no-lock-message: Your item was previously locked!
unlock-message: Your item has been successfully unlocked!
no-unlock-message: Your item has not been locked before!
item-hand-message: You need to hold the item in your hand to unlock!

#Lore of item when locked
item-lore: LOCKED
# The item locked will not be able to interact with the itemframe if this is true
no-touch: true
# The when the item is locked, it cannot be put in the chest if this is true
no-change-inventory: true
...
